spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: false
        enable_lazy_load_no_trans: true





